// 100 soruluk varsayılan deste
// Arkadaş ortamı için: kızıştırıcı, utandırıcı, derin, samimi
// Kullanıcı istediği soruyu silip/ekleyebilir

export const DEFAULT_QUESTIONS: string[] = [
  // -------- Ortam kızıştırıcı / karşılaştırma (1-20) --------
  "Bu ortamdaki en seksi kim? İsim ver.",
  "Bu ortamdaki en güzel/yakışıklı kim? İsim ver.",
  "Bu ortamdaki en çirkin kim? Yuvarlama, isim ver.",
  "Gruptaki en dramatik kim?",
  "Gruptaki en cimri kim?",
  "Gruptaki en yalancı kim?",
  "Gruptaki en dedikoducu kim?",
  "Gruptaki en tembel kim?",
  "Gruptaki en çapkın kim?",
  "Gruptaki en bencil kim?",
  "Gruptaki en sahte kim?",
  "Gruptaki en şımarık kim?",
  "Gruptaki en iyi giyinen kim?",
  "Gruptaki en kötü giyinen kim?",
  "Gruptaki en kötü şoför kim?",
  "Grubun annesi/babası gibi davranan kim?",
  "Masadan biri reality show'a çıksa kim yırtar?",
  "Masadan en iyi öpüşen kim sence? Tahmin yap.",
  "Masadan en kötü öpüşen kim sence? Tahmin yap.",
  "Senden açık ara daha başarılı olacağını düşündüğün grup üyesi kim?",

  // -------- Aşk / flört / ilişki (21-35) --------
  "En son kime aşık olup söyleyemedin?",
  "Gruptan birine hiç sempati duydun mu? Sadece evet/hayır.",
  "Şu an odada olmayan bir eksinle gruptakiler tanışsa nasıl tepki verirdin?",
  "Hiç aldattığın biri oldu mu?",
  "Şu anki partnerin dışında, masada biriyle olsan kim olurdu?",
  "En son ne zaman birini öptün?",
  "En utanç verici flört deneyimin neydi?",
  "İlk aşkının ismini söyle.",
  "Hâlâ takip ettiğin bir ex var mı? Neden?",
  "Instagram DM'de en son kiminle konuştun? Aç göster.",
  "Hayalindeki kişi bugün kapıda belirse ne yapardın?",
  "Birine karşı söyleyemediğin bir şey var mı şu an?",
  "Tek taraflı sevdiğin biri var mı şu an? Sadece evet/hayır.",
  "Okul yıllarında seni en çok gıcık eden kişi kimdi, neden?",
  "Hiç birine yanlışlıkla 'seni seviyorum' dedin mi?",

  // -------- Utandırıcı / itiraf (36-55) --------
  "Son 1 yılda yaptığın en utanç verici şey neydi?",
  "Alkolün etkisiyle yaptığın en büyük rezillik?",
  "Büyüklerinin yanında yaşadığın en rezil an?",
  "Çocukken inandığın en saçma şey?",
  "Birinin yanında düştüğün en beter an?",
  "Annen/baban odana habersiz girseydi bugün ne görürdü?",
  "Yanlış kişiye mesaj gönderip yandığın oldu mu? Anlat.",
  "Telefonunda en son ne arattın? Göster.",
  "En son aradığın 5 kişiyi göster.",
  "Son sildiğin mesaj neydi, kime?",
  "En son kime stalk attın?",
  "Galeriden en utanç verici fotoğrafını aç, göster.",
  "Gruba ait bir utanç verici sırrını paylaş.",
  "Okul veya iş hayatında en büyük başarısızlığın?",
  "Hiç ağlayarak bir şey için yalvardın mı? Ne için?",
  "Birinin yüzüne söyleyemeyip arkasından söylediğin en ağır laf?",
  "Sarhoşken hatırlamadığın bir gece var mı? Anlat ne yapmışsın.",
  "En utandığın çocukluk fotoğrafını göster.",
  "Hayatında sakladığın bir sır, bugün söylersen rahat hissedersin.",
  "En son ne zaman rezil oldun?",

  // -------- Derin / rahatsız edici (56-75) --------
  "En son ne için ağladın?",
  "En büyük korkun ne?",
  "En büyük pişmanlığın?",
  "Ölmeden önce yapmak istediğin tek şey?",
  "Bugün ölsen en çok özleyeceğin kişi kim?",
  "Masadan birinin olmadığını hayal et — kim olurdu?",
  "Aileni saymazsak en sevdiğin insan kim?",
  "Şu an hayatından kesip atmak istediğin ne?",
  "10 yıl sonra bu masada herkesi görmek istiyor musun? Kim eksik olurdu?",
  "Kimseye söylemediğin bir hayalin var mı?",
  "İnsanlara kendin hakkında söylediğin en büyük yalan?",
  "Ailenle ilgili utandığın bir şey var mı?",
  "Hiç biriyle konuşmayı tamamen kestin mi? Neden?",
  "Hayatında geri alabileceğin tek hata hangisi olurdu?",
  "Çocuğun olsa kendinden hangi özelliği almasını istemezdin?",
  "En çok kimi yanılttığını düşünüyorsun?",
  "En büyük güvensizliğin ne?",
  "Kendinde en nefret ettiğin şey?",
  "Bir gün uyanıp zengin olsan hayatından kimi çıkarırdın?",
  "Sence bugünkü hâlinden 5 yıl önceki sen memnun olur muydu?",

  // -------- Sosyal / provokatif (76-90) --------
  "Masadan birinin sevgilisiyle çıkar mıydın? Kimle?",
  "Masadan biri sana itiraf etse kim şaşırtmaz?",
  "Kaza geçirsen ve masadan tek kişi ziyarete gelse kim olurdu?",
  "Masadan kime 1 milyon lira borç verirdin?",
  "Masadan kimi kefil gösterirdin?",
  "Masadan kimi silsen kimse fark etmez?",
  "Masadan en çok kiminle kavga edersin?",
  "Bu odada kim en uzun süre çenesini kapalı tutabilir sence?",
  "En zor gününde hangimiz yanında oldu?",
  "En son hangi arkadaşını çekiştirdin? (masadan biri olabilir)",
  "Masadan biri bir gün sana ihanet etse kim olurdu?",
  "Hayatına devam etsen bu masadan kimi görmeyi bırakırdın?",
  "Evlenirken sağdıcın/nedimen masadan kim olurdu?",
  "Cenazene bu masadan gelmeyeceğini düşündüğün biri var mı?",
  "Masadakilere küçükten büyüğe güven sıralaması yap.",

  // -------- Eğlenceli / açığa çıkarıcı (91-100) --------
  "Tek seferlik bir süper gücün olsa ne olurdu, nasıl kullanırdın?",
  "Son 1 ayın en iyi günü hangisi?",
  "5 yıl önceki kendine mesaj atabilsen ne yazardın?",
  "Hiç birine 'senin gibi olmak isterdim' dedin mi? Kime?",
  "Hayatından bir kişiyi silebilsen kim olurdu?",
  "Cebindeki son 100 TL'yi şu an ne yapardın?",
  "Hayatından bir günü yeniden yaşasan hangisi?",
  "Son 6 ayda kendinde en büyük değişiklik ne?",
  "Tek kelimeyle kendini anlat.",
  "Bu gece başlarken 'bu soruyu ben çekmem inşallah' dediğin soru hangisiydi?"
];
